name: CI / CD Test
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker Image
        run: |
          docker build -t tester/my-api-app .
          docker save -o my-api-app.tar tester/my-api-app

      - name: Copy Docker Image to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "my-api-app.tar"
          target: "/opt"

      - name: Deploy Docker Image on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i /opt/my-api-app.tar
            rm /opt/my-api-app.tar
            docker kill $(docker ps -q)
            docker run -d -p 0.0.0.0:8000:8000 tester/my-api-app:latest